Script started on Sun 22 Nov 2015 11:25:53 PM PST
]0;mcast052@hammer:~/CS100/Assignment1/rshell[?1034h[mcast052@hammer rshell]$ bin/rshell
mcast052@hammer.cs.ucr.edu$ (eh cho A && echo B) || (echo C && echo D)
A
B
mcast052@hammer.cs.ucr.edu$ poop || (echo A; ls && goodbye  ) || echo fail
execvp failed in child: No such file or directory
A
bin  LICENSE  Makefile	precedence_test.script	README.md  src	tests
execvp failed in child: No such file or directory
fail
mcast052@hammer.cs.ucr.edu$ echo hello world && (ls && echo poop || echo fail) || echo past failed
hello world
bin  LICENSE  Makefile	precedence_test.script	README.md  src	tests
poop
mcast052@hammer.cs.ucr.edu$ echo no; (echo yes)
no
yes
mcast052@hammer.cs.ucr.edu$ (echo hi
Syntax error
mcast052@hammer.cs.ucr.edu$ echo hi)
Syntax error
mcast052@hammer.cs.ucr.edu$ ls; echo "hello world" && (command
Syntax error
mcast052@hammer.cs.ucr.edu$ exit
]0;mcast052@hammer:~/CS100/Assignment1/rshell[mcast052@hammer rshell]$ exit
exit

Script done on Sun 22 Nov 2015 11:34:26 PM PST
